# Generated by Django 3.0.7 on 2020-07-25 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.IntegerField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=50)),
                ('facility_description', models.CharField(blank=True, max_length=100, null=True)),
                ('locked_for_edit', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facility',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.CharField(blank=True, max_length=200, null=True)),
                ('project_address', models.CharField(blank=True, max_length=100, null=True)),
                ('project_city', models.CharField(blank=True, max_length=50, null=True)),
                ('project_pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('project_status', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'project',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=20)),
                ('zone_description', models.CharField(blank=True, max_length=100, null=True)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataload.Facility')),
            ],
            options={
                'db_table': 'zone',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataload.Project'),
        ),
    ]
